services:
  postgres:
    image: postgres:15-alpine
    container_name: dev_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
      TZ: Asia/Taipei
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: dev_pg_adminer
    restart: always
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: dev_nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${FRONTEND_PATH}:/usr/share/nginx/html:ro
      - ./nginx/default.dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - adminer

volumes:
  postgres_data:
