# Generated by Django 6.0.4 on 2026-05-06 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='廠商名稱')),
                ('tax_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='統一編號')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡電話')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='負責人名稱')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '廠商',
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='BatchInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('original_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('remaining_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('received_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '批號庫存',
                'db_table': 'batch_inventories',
            },
        ),
        migrations.CreateModel(
            name='BatchInventoryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.batchinventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_inventory_logs',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boms',
            },
        ),
        migrations.CreateModel(
            name='BOMLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.bom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bom_logs',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('RAW', '原物料'), ('SEMI', '半成品'), ('PRODUCT', '最終產品'), ('PACK', '包材')], max_length=10)),
                ('unit', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_material', to='factory.material'),
        ),
        migrations.AddField(
            model_name='bom',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_product', to='factory.material'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material'),
        ),
        migrations.CreateModel(
            name='MaterialLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_logs',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirementPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_info', models.JSONField()),
                ('batch_inventory_info', models.JSONField()),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material')),
            ],
            options={
                'verbose_name': '物料需求單',
                'db_table': 'mrp_plans',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirementPlanLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mrp_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.materialrequirementplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mrp_logs',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, null=True, unique=True)),
                ('target_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_PROGRESS', '生產中'), ('DONE', '已完成')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material')),
            ],
            options={
                'verbose_name': '生產單',
                'db_table': 'production_orders',
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planned_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('actual_qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('waste_qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.batchinventory')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usages', to='factory.productionorder')),
            ],
            options={
                'verbose_name': '生產用料紀錄',
                'db_table': 'production_material_usages',
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.productionorder')),
            ],
            options={
                'db_table': 'production_logs',
            },
        ),
        migrations.CreateModel(
            name='LogisticsOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logistics_provider', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.productionorder')),
            ],
            options={
                'verbose_name': '物流單',
                'verbose_name_plural': '物流單',
                'db_table': 'logistics_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('expected_date', models.DateField(db_index=True)),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material')),
            ],
            options={
                'verbose_name': '採購訂單',
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('ADMIN', '行政'), ('MANUFACTURING', '製造'), ('RD', '研發'), ('PURCHASING', '採購'), ('EMPLOYER', '老闆')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='VendorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.vendor')),
            ],
            options={
                'db_table': 'vendor_logs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('parent', 'child')},
        ),
    ]
