# Generated by Django 6.0.4 on 2026-05-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_vendor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinventory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='received_date',
            field=models.DateField(),
        ),
    ]
