# Generated by Django 6.0.4 on 2026-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_batchinventory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': '客戶'},
        ),
        migrations.AddField(
            model_name='vendor',
            name='code',
            field=models.CharField(default='PLACEHOLDER', max_length=64, verbose_name='客戶代號'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='客戶名稱'),
        ),
    ]
