# Generated by Django 6.0.4 on 2026-05-19 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_vendor_options_vendor_code_alter_vendor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequirementplan',
            name='mrp_id',
            field=models.CharField(default='TEMP-00000000', max_length=50, unique=True, verbose_name='MRP單號'),
        ),
        migrations.AddField(
            model_name='materialrequirementplan',
            name='parent_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='母單號'),
        ),
        migrations.AddIndex(
            model_name='materialrequirementplan',
            index=models.Index(fields=['mrp_id', 'parent_id'], name='mrp_plans_mrp_id_5062e1_idx'),
        ),
    ]
