# Generated by Django 6.0.4 on 2026-05-25 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_materialrequirementplan_mrp_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('applicant', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('WAITING', '等待進貨'), ('STOCKED', '已經入庫')], default='WAITING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_requests',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='Kg', max_length=10)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='factory.purchaserequisition')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_requisition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.purchaserequisition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
