# Generated by Django 6.0.4 on 2026-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_purchaserequisition_purchaserequisitionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
