# Generated by Django 6.0.4 on 2026-05-26 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_purchaserequisitionitem_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='materials_info',
            field=models.JSONField(default=list, verbose_name='原物料與用量資訊'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='parent_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='母生產單號'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='生產單號'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['order_number', 'parent_id'], name='production__order_n_f6496a_idx'),
        ),
    ]
