# Generated by Django 6.0.4 on 2026-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_productionorder_materials_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_info',
            field=models.JSONField(default=dict, verbose_name='客戶與物流資訊'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
