# Generated by Django 6.0.4 on 2026-05-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_purchaseorder_vendor_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_info',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='vendor_info',
            field=models.JSONField(default=None, verbose_name='客戶與物流資訊'),
        ),
    ]
