# Generated by Django 6.0.4 on 2026-06-01 05:04

import factory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_remove_purchaseorder_vendor_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinventory',
            name='expiration_date',
            field=models.DateField(default=factory.models.get_default_expiration_date),
        ),
    ]
