# Generated by Django 6.0.4 on 2026-06-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_batchinventory_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorder',
            old_name='actual_yield',
            new_name='actual_qty',
        ),
        migrations.DeleteModel(
            name='ProductionMaterialUsage',
        ),
    ]
