# Generated by Django 6.0.4 on 2026-06-03 06:43

import factory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_rename_actual_yield_productionorder_actual_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_date',
            field=models.DateTimeField(default=factory.models.get_default_onboarding_date),
        ),
    ]
