# Generated by Django 6.0.4 on 2026-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_userprofile_onboarding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='adjustment_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='盈虧數量'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='adjustment_type',
            field=models.CharField(choices=[('NONE', '無調整'), ('PROFIT', '盤盈'), ('LOSS', '盤虧')], default='NONE', max_length=10, verbose_name='調整狀態'),
        ),
    ]
