# Generated by Django 6.0.4 on 2026-07-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_remove_productionorder_adjustment_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
