# Generated by Django 6.0.4 on 2026-07-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0016_material_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisitionitem',
            name='material_name',
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_items', to='factory.material'),
            preserve_default=False,
        ),
    ]
