# Generated by Django 6.0.4 on 2026-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0017_remove_purchaserequisitionitem_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
