# Generated by Django 6.0.4 on 2026-07-15 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_purchaserequisitionitem_purchased_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_number', models.CharField(max_length=50, unique=True, verbose_name='單據編號')),
                ('note_date', models.DateField(verbose_name='單據日期')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='本次出貨數量')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='單位')),
                ('spec', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='單價')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='批號編號')),
                ('customer_info', models.JSONField(default=dict, verbose_name='客戶與收件資訊')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='合計金額')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='營業稅')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='銷貨總額')),
                ('document_note', models.TextField(blank=True, null=True, verbose_name='單據備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_notes', to='factory.productionorder', verbose_name='關聯生產單')),
            ],
            options={
                'verbose_name': '銷貨單',
                'db_table': 'delivery_notes',
            },
        ),
    ]
