# Generated by Django 6.0.4 on 2026-07-17 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0020_deliverynotelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='單據編號')),
                ('order_date', models.DateField(verbose_name='單據日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交貨日期')),
                ('customer_info', models.JSONField(default=dict, verbose_name='客戶資訊')),
                ('spec', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='訂單總數量')),
                ('unit', models.CharField(default='KG', max_length=10, verbose_name='單位')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='單價')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='合計金額')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='營業稅')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='總計金額')),
                ('document_note', models.TextField(blank=True, null=True, verbose_name='單據備註')),
                ('logistics_info', models.JSONField(default=dict, verbose_name='物流設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('mrp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='factory.materialrequirementplan', verbose_name='物料需求單(MRP)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material', verbose_name='訂購產品')),
            ],
            options={
                'verbose_name': '客戶訂貨單',
                'db_table': 'customer_orders',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.customerorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_order_logs',
            },
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['order_number'], name='customer_or_order_n_8a1c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['order_date'], name='customer_or_order_d_43b6b2_idx'),
        ),
    ]
