# Generated by Django 6.0.4 on 2026-07-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0021_customerorder_customerorderlog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderlog',
            old_name='production_order',
            new_name='customer_order',
        ),
        migrations.RenameField(
            model_name='deliverynotelog',
            old_name='production_order',
            new_name='delivery_notes',
        ),
    ]
