# Generated by Django 6.0.4 on 2026-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0022_rename_production_order_customerorderlog_customer_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=models.CharField(max_length=50, verbose_name='單據編號'),
        ),
    ]
