# Generated by Django 6.0.4 on 2026-07-24 06:41

import django.db.models.deletion
import factory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_alter_customerorder_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': '配方清單'},
        ),
        migrations.AlterModelOptions(
            name='logisticsorder',
            options={'verbose_name': '物流單'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequisition',
            options={'verbose_name': '請購單'},
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='批號'),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='expiration_date',
            field=models.DateField(default=factory.models.get_default_expiration_date, verbose_name='有效期限'),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material', verbose_name='物料'),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='original_qty',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='初始數量'),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='received_date',
            field=models.DateField(verbose_name='入庫日期'),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='剩餘數量'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_material', to='factory.material', verbose_name='半成品'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_product', to='factory.material', verbose_name='成品'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='quantity_required',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='需求數量'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='logisticsorder',
            name='details',
            field=models.TextField(verbose_name='物流詳情'),
        ),
        migrations.AlterField(
            model_name='logisticsorder',
            name='logistics_provider',
            field=models.CharField(max_length=100, verbose_name='物流商'),
        ),
        migrations.AlterField(
            model_name='logisticsorder',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.productionorder', verbose_name='關聯生產單'),
        ),
        migrations.AlterField(
            model_name='logisticsorder',
            name='vendor_name',
            field=models.CharField(max_length=100, verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='物料代號'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='物料名稱'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('RAW', '原物料'), ('SEMI', '半成品'), ('PRODUCT', '最終產品'), ('PACK', '包材')], max_length=10, verbose_name='物料類型'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='materialrequirementplan',
            name='batch_inventory_info',
            field=models.JSONField(verbose_name='批號資訊'),
        ),
        migrations.AlterField(
            model_name='materialrequirementplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material', verbose_name='需求物料'),
        ),
        migrations.AlterField(
            model_name='materialrequirementplan',
            name='required_qty',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='需求數量'),
        ),
        migrations.AlterField(
            model_name='materialrequirementplan',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='materialrequirementplan',
            name='vendor_info',
            field=models.JSONField(verbose_name='客戶資訊'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='actual_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='實際生產量'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material', verbose_name='生產產品'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('IN_PROGRESS', '生產中'), ('DONE', '已完成')], db_index=True, default='DRAFT', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='target_qty',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='預計生產量'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計到貨日期'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material', verbose_name='採購物料'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_qty',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='採購數量'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(db_index=True, default='DRAFT', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='applicant',
            field=models.CharField(max_length=50, verbose_name='申請人'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='request_date',
            field=models.DateField(verbose_name='申請日期'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('WAITING', '等待進貨'), ('STOCKED', '已經入庫')], default='WAITING', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計到貨日期'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_items', to='factory.material', verbose_name='請購物料'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='採購單價'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='factory.purchaserequisition', verbose_name='請購單'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='供應商'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='unit',
            field=models.CharField(default='Kg', max_length=10, verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('ADMIN', '行政'), ('MANUFACTURING', '製造'), ('RD', '研發'), ('PURCHASING', '採購'), ('EMPLOYER', '老闆')], max_length=20, verbose_name='所屬部門'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='帳號狀態'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='onboarding_date',
            field=models.DateTimeField(default=factory.models.get_default_onboarding_date, verbose_name='到職日'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否移除'),
        ),
    ]
