# Generated by Django 6.0.4 on 2026-07-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_alter_bom_options_alter_logisticsorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequirementplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='status',
        ),
        migrations.AddField(
            model_name='bom',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否啟用'),
        ),
        migrations.AddField(
            model_name='materialrequirementplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
    ]
