# Generated by Django 6.0.4 on 2026-07-24 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0025_remove_materialrequirementplan_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchinventory',
            name='batch_number',
            field=models.CharField(max_length=50, verbose_name='批號'),
        ),
        migrations.AddConstraint(
            model_name='batchinventory',
            constraint=models.UniqueConstraint(fields=('material', 'batch_number'), name='unique_material_batch'),
        ),
    ]
