# Generated by Django 6.0.4 on 2026-07-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0026_alter_batchinventory_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('RAW', '原物料'), ('SEMI', '半成品'), ('PRODUCT', '成品'), ('PACK', '包材')], max_length=10, verbose_name='物料類型'),
        ),
    ]
