# Generated by Django 6.0.4 on 2026-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0027_alter_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequirementplan',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('converted', '已轉換')], default='pending', max_length=20, verbose_name='狀態'),
        ),
    ]
