# Generated by Django 6.0.4 on 2026-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_materialrequirementplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchinventorylog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bomlog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorderlog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynotelog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiallog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequirementplanlog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionlog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorlog',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
