# Generated by Django 6.0.4 on 2026-07-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0029_alter_batchinventorylog_action_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spec', models.TextField(blank=True, help_text='如: 1KG*25包/箱', null=True, verbose_name='產品規格')),
                ('sales_unit', models.CharField(default='箱', max_length=20, verbose_name='銷售單位')),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='銷售單價')),
                ('label_info', models.JSONField(blank=True, default=dict, verbose_name='標籤資訊')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_profile', to='factory.material', verbose_name='關聯成品')),
            ],
            options={
                'verbose_name': '成品專屬資訊',
                'db_table': 'product_profiles',
            },
        ),
    ]
