# Generated by Django 6.0.4 on 2026-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0030_productprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='配方基數'),
        ),
    ]
