# Generated by Django 6.0.4 on 2026-08-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0031_bom_base_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverynote',
            old_name='unit_price',
            new_name='sales_price',
        ),
    ]
