# Generated by Django 6.0.4 on 2026-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0032_rename_unit_price_deliverynote_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('waiting', '待進貨'), ('stocked', '已入庫')], default='waiting', max_length=20, verbose_name='單據狀態'),
        ),
    ]
