# Generated by Django 6.0.4 on 2026-08-11 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0033_purchaserequisition_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='material',
            name='additive_license_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='添加物許可證號'),
        ),
        migrations.AddField(
            model_name='material',
            name='allergen_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='過敏原資訊'),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述 (成分來源)'),
        ),
        migrations.AddField(
            model_name='material',
            name='english_name',
            field=models.CharField(max_length=100, null=True, verbose_name='物料英文名稱'),
        ),
        migrations.AddField(
            model_name='material',
            name='license_valid_date',
            field=models.DateField(blank=True, null=True, verbose_name='許可證效期'),
        ),
        migrations.AddField(
            model_name='material',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='產地'),
        ),
        migrations.AddField(
            model_name='material',
            name='phase',
            field=models.CharField(choices=[('IN_DEV', '開發'), ('IN_PROD', '正式')], default='IN_PROD', max_length=10, verbose_name='物料使用階段'),
        ),
        migrations.AddField(
            model_name='material',
            name='product_registration_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='產品登錄號'),
        ),
        migrations.AddField(
            model_name='material',
            name='storage_life',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='保存期限'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='sales_pack_unit',
            field=models.CharField(default='包', max_length=10, verbose_name='銷售輔助單位'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='factory.vendor', verbose_name='購買客戶'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(default='未命名物料', max_length=100, verbose_name='物料名稱'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='KG', max_length=10, verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_profiles', to='factory.material', verbose_name='關聯成品'),
        ),
        migrations.AlterField(
            model_name='productprofile',
            name='sales_unit',
            field=models.CharField(default='箱', max_length=10, verbose_name='銷售單位'),
        ),
        migrations.CreateModel(
            name='MaterialProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='供應商名稱')),
                ('code', models.CharField(default='PLACEHOLDER', max_length=64, verbose_name='供應商代號')),
                ('fax', models.CharField(blank=True, max_length=10, null=True, verbose_name='傳真號碼')),
                ('tax_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='統一編號')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司地址')),
                ('invoice_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='發票地址')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='送貨地址')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡電話')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='負責人名稱')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡 Email')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='銀行名稱')),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='銀行帳號')),
                ('note', models.TextField(verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '原物料供應商',
                'db_table': 'material_providers',
            },
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='material_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='factory.materialprovider', verbose_name='供應商'),
        ),
    ]
