# Generated by Django 6.0.4 on 2026-08-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0034_remove_material_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='物料英文名稱'),
        ),
    ]
