# Generated by Django 6.0.4 on 2026-08-15 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0035_alter_material_english_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='單據編號')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='單據日期')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('CONFIRMED', '已確認/成立')], default='DRAFT', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='經辦人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.vendor', verbose_name='客戶')),
            ],
            options={
                'db_table': 'customer_quotations',
            },
        ),
        migrations.CreateModel(
            name='CustomerQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs_breakdown', models.JSONField(default=dict, verbose_name='成本明細結構')),
                ('pricing_multiplier', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='客戶報價常數')),
                ('final_price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最終報價單價/KG')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.material', verbose_name='報價產品')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factory.customerquotation')),
            ],
            options={
                'db_table': 'customer_quotation_items',
            },
        ),
    ]
