# Generated by Django 6.0.4 on 2026-08-15 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0036_customerquotation_customerquotationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquotation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
        migrations.CreateModel(
            name='CustomerQuotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='factory.customerquotation', verbose_name='報價單')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
            ],
            options={
                'db_table': 'customer_quotation_logs',
            },
        ),
    ]
