# Generated by Django 6.0.4 on 2026-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0037_customerquotation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquotationitem',
            name='spec',
            field=models.CharField(blank=True, help_text='如：0.10KG*110包/箱', max_length=100, null=True, verbose_name='包裝規格'),
        ),
    ]
