# Generated by Django 6.0.4 on 2026-08-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0038_customerquotationitem_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='sales_pack_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='如: 1KG*25包/箱，則填25(包)', max_digits=10, verbose_name='銷售輔助單位數量'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='sales_unit_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='如: 1KG*25包/箱，則填1(箱)', max_digits=10, verbose_name='銷售單位數量'),
        ),
    ]
