# Generated by Django 6.0.4 on 2026-08-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0039_productprofile_sales_pack_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_additive',
            field=models.BooleanField(default=False, verbose_name='是否為法規添加物'),
        ),
        migrations.AddField(
            model_name='material',
            name='legal_limit_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='如二矽法規上限2%，請填 2.0', max_digits=6, null=True, verbose_name='法規上限比例(%)'),
        ),
    ]
