# Generated by Django 6.0.4 on 2026-08-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0040_material_is_additive_material_legal_limit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='pack_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='若物料為包材(PACK)，請輸入此包材單一個數可裝載之重量(KG)，如：500g包裝袋請填 0.5', max_digits=10, null=True, verbose_name='包材容量/淨重(KG)'),
        ),
    ]
