# Generated by Django 6.0.4 on 2026-08-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0041_material_pack_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprofile',
            name='sales_pack_unit',
            field=models.CharField(default='箱', max_length=10, verbose_name='銷售輔助單位'),
        ),
    ]
