# Generated by Django 6.0.4 on 2026-08-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0043_alter_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('RAW', '原物料'), ('SEMI', '半成品'), ('PRODUCT', '成品'), ('PACK', '包材'), ('STICKER', '標籤貼紙'), ('OTHER', '其他')], max_length=10, verbose_name='物料類型'),
        ),
    ]
