# Generated by Django 6.0.4 on 2026-08-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0044_alter_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nutrition_fact',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='八大營養價值標示'),
        ),
    ]
