# Generated by Django 6.0.4 on 2026-08-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0045_material_nutrition_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='inner_pack',
            field=models.ForeignKey(blank=True, help_text='對應 sales_pack_unit (如: 1KG用厚鋁箔袋)。負責定義『包/袋』的實體物料。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_pack_profiles', to='factory.material', verbose_name='內層包材 (AUX)'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='outer_pack',
            field=models.ForeignKey(blank=True, help_text='對應 sales_unit (如: 5號標準外箱)。負責定義『箱/桶』的實體物料。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outer_pack_profiles', to='factory.material', verbose_name='外層包材 (MAJOR)'),
        ),
    ]
