# Generated by Django 6.0.4 on 2026-08-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0046_productprofile_inner_pack_productprofile_outer_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquotationitem',
            name='inner_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_inner_packs', to='factory.material', verbose_name='內層實體包材'),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='outer_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_outer_packs', to='factory.material', verbose_name='外層實體包材'),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='sales_pack_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='每銷售單位含包裝數'),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='sales_pack_unit',
            field=models.CharField(default='包', max_length=10, verbose_name='包裝單位'),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='sales_unit',
            field=models.CharField(default='箱', max_length=10, verbose_name='銷售單位'),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='sales_unit_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='銷售單位數量'),
        ),
    ]
