# Generated by Django 6.0.4 on 2026-08-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0047_customerquotationitem_inner_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='qc_brix_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Brix 上限'),
        ),
        migrations.AddField(
            model_name='material',
            name='qc_brix_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Brix 下限'),
        ),
        migrations.AddField(
            model_name='material',
            name='qc_dilution_ratio',
            field=models.CharField(blank=True, help_text='如: (1:1), (1:5) 或 (原)', max_length=20, null=True, verbose_name='檢測稀釋比例'),
        ),
        migrations.AddField(
            model_name='material',
            name='qc_microbiology',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='微生物與其他法定檢驗標準'),
        ),
        migrations.AddField(
            model_name='material',
            name='qc_moisture_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='如: 10 代表 <10%', max_digits=5, null=True, verbose_name='水分上限(%)'),
        ),
        migrations.AddField(
            model_name='material',
            name='qc_salt_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='鹽度 上限'),
        ),
        migrations.AddField(
            model_name='material',
            name='qc_salt_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='鹽度 下限'),
        ),
    ]
