# Generated by Django 6.0.4 on 2026-08-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0048_material_qc_brix_max_material_qc_brix_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprofile',
            name='label_info',
        ),
    ]
