# Generated by Django 6.0.4 on 2026-08-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0049_remove_productprofile_label_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialprovider',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
