# Generated by Django 6.0.4 on 2026-09-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0050_alter_materialprovider_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinventory',
            name='aux_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='1 單位包裝含有多少基本單位，如 1 袋 30KG 填 30', max_digits=10, null=True, verbose_name='輔助數量'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='aux_unit',
            field=models.CharField(blank=True, help_text='如：袋、箱', max_length=20, null=True, verbose_name='包裝輔助單位'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='in_stock_spec',
            field=models.CharField(blank=True, help_text='如：30KG/袋、台益行: 20KG/袋', max_length=150, null=True, verbose_name='入庫包裝規格'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='note',
            field=models.TextField(blank=True, help_text='人工備註交接、成分紀錄等', null=True, verbose_name='進貨備註'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='total_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='若基本單位非KG（如：包），請填寫單一基本單位的KG數，用以輔助計算', max_digits=10, null=True, verbose_name='產品總KG'),
        ),
    ]
