# Generated by Django 6.0.4 on 2026-09-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0052_remove_batchinventory_aux_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisitionitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionitem',
            name='total_kg',
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='aux_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='單件基本重'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='aux_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='輔助單位'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='in_stock_spec',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='入庫規格'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='進貨備註'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='package_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='入庫件數'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='package_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='採購件數'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='aux_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='單件基本重'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='aux_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='輔助單位'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='in_stock_spec',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='參考規格'),
        ),
    ]
