# Generated by Django 6.0.4 on 2026-09-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0053_remove_purchaserequisitionitem_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinventory',
            name='source_pr_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generated_batch', to='factory.purchaserequisitionitem'),
        ),
    ]
