# Generated by Django 6.0.4 on 2026-09-02 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0054_batchinventory_source_pr_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProviderQuotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_date', models.DateField(blank=True, null=True, verbose_name='報價日期')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='報價效期')),
                ('effective_date', models.DateField(verbose_name='系統生效日期')),
                ('is_tax_included', models.BooleanField(default=True, verbose_name='是否含稅')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='整單備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='factory.materialprovider', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '供應商報價單',
                'db_table': 'material_provider_quotations',
            },
        ),
        migrations.CreateModel(
            name='MaterialProviderPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='報價規格')),
                ('aux_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='輔助單位')),
                ('aux_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='單件基本重')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='廠商原始報價')),
                ('quoted_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='報價單位')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='系統基本單價')),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_prices', to='factory.material', verbose_name='物料')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factory.materialproviderquotation')),
            ],
            options={
                'db_table': 'material_provider_prices',
            },
        ),
    ]
