# Generated by Django 6.0.4 on 2026-09-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0055_materialproviderquotation_materialproviderprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchQCRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_date', models.DateField(verbose_name='取樣日期')),
                ('test_date', models.DateField(verbose_name='檢測日期')),
                ('is_appearance_passed', models.BooleanField(default=True, verbose_name='外觀/色澤判定')),
                ('is_flavor_passed', models.BooleanField(default=True, verbose_name='風味/氣味判定')),
                ('actual_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='實際水分(%)')),
                ('actual_brix', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='實際糖度(Brix)')),
                ('actual_salt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='實際鹽度(%)')),
                ('actual_microbiology', models.JSONField(blank=True, default=dict, null=True, verbose_name='實際微生物檢驗結果')),
                ('is_passed', models.BooleanField(default=True, verbose_name='最終判定(合格/不合格)')),
                ('remark', models.TextField(blank=True, help_text='如: 綜合此檢測落點，修正鹽度規格', null=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qc_records', to='factory.batchinventory', verbose_name='檢驗批號')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inspected_qcs', to=settings.AUTH_USER_MODEL, verbose_name='檢驗人員')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qc_records', to='factory.material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '批號品管檢驗紀錄',
                'db_table': 'batch_qc_records',
                'ordering': ['-test_date', '-id'],
            },
        ),
    ]
