# Generated by Django 6.0.4 on 2026-09-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0056_batchqcrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchqcrecord',
            name='is_appearance_passed',
        ),
        migrations.RemoveField(
            model_name='batchqcrecord',
            name='is_flavor_passed',
        ),
    ]
