# Generated by Django 6.0.4 on 2026-09-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0057_remove_batchqcrecord_is_appearance_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='物料備註'),
        ),
    ]
