# Generated by Django 6.0.4 on 2026-09-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0058_bom_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='set_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='自訂單位成本'),
        ),
    ]
