# Generated by Django 6.0.4 on 2026-09-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0059_bom_set_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.material', verbose_name='報價產品'),
        ),
        migrations.AlterField(
            model_name='customerquotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='factory.customerquotation'),
        ),
        migrations.AlterField(
            model_name='customerquotationitem',
            name='sales_pack_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='每銷售單位含包裝數'),
        ),
        migrations.AlterField(
            model_name='customerquotationitem',
            name='sales_pack_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='包裝單位'),
        ),
    ]
