# Generated by Django 6.0.4 on 2026-09-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0060_alter_customerquotationitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='dietary_type',
            field=models.CharField(blank=True, choices=[('MEAT', '葷食'), ('VEGAN', '全素'), ('LACTO', '奶素'), ('OVO', '蛋素'), ('LACTO_OVO', '蛋奶素'), ('FIVE_PUNGENT', '植物五辛素')], help_text='如為複合原料，請依據成分中最嚴格的葷素級別標示', max_length=20, null=True, verbose_name='素食類別'),
        ),
        migrations.AddField(
            model_name='material',
            name='storage_method',
            field=models.CharField(choices=[('ROOM_TEMP', '常溫'), ('REFRIGERATED', '冷藏'), ('FROZEN', '冷凍')], default='ROOM_TEMP', help_text='預設為常溫', max_length=20, verbose_name='保存方式'),
        ),
    ]
