# Generated by Django 6.0.4 on 2026-09-09 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0061_material_dietary_type_material_storage_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='成分名稱')),
                ('source_type', models.CharField(choices=[('TFDA', '食藥署資料庫'), ('MANUAL', '手動建檔')], default='MANUAL', max_length=10, verbose_name='資料來源')),
                ('tfda_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='TFDA代碼')),
                ('nutrition_fact', models.JSONField(blank=True, default=dict, null=True, verbose_name='八大營養素')),
                ('allergen_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='法定過敏原')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='建檔人')),
            ],
            options={
                'verbose_name': '成分',
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='MaterialIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.ingredient', verbose_name='成分')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material_ingredients', to='factory.material', verbose_name='原物料')),
            ],
            options={
                'verbose_name': '原物料成分明細',
                'db_table': 'material_ingredients',
            },
        ),
    ]
