# Generated by Django 6.0.4 on 2026-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0062_ingredient_materialingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='additive_license_no',
        ),
        migrations.RemoveField(
            model_name='material',
            name='is_additive',
        ),
        migrations.RemoveField(
            model_name='material',
            name='legal_limit_percent',
        ),
        migrations.RemoveField(
            model_name='material',
            name='license_valid_date',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='additive_license_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='許可證號'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_additive',
            field=models.BooleanField(default=False, verbose_name='是否為法規添加物'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='legal_limit_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='法規上限(%)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='license_valid_date',
            field=models.DateField(blank=True, null=True, verbose_name='許可證效期'),
        ),
    ]
