# Generated by Django 6.0.4 on 2026-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0063_remove_material_additive_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialingredient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
    ]
