# Generated by Django 6.0.4 on 2026-09-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0064_materialingredient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='selected_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.materialproviderprice', verbose_name='參考廠商報價'),
        ),
    ]
