# Generated by Django 6.0.4 on 2026-09-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0065_bom_selected_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='qc_brix_max',
        ),
        migrations.RemoveField(
            model_name='material',
            name='qc_brix_min',
        ),
        migrations.RemoveField(
            model_name='material',
            name='qc_dilution_ratio',
        ),
        migrations.RemoveField(
            model_name='material',
            name='qc_microbiology',
        ),
        migrations.RemoveField(
            model_name='material',
            name='qc_moisture_max',
        ),
        migrations.RemoveField(
            model_name='material',
            name='qc_salt_max',
        ),
        migrations.RemoveField(
            model_name='material',
            name='qc_salt_min',
        ),
        migrations.AddField(
            model_name='material',
            name='qc_standards',
            field=models.JSONField(blank=True, default=list, help_text='以 JSON 陣列定義此成品的檢驗項目與合格區間', null=True, verbose_name='預設品管檢驗標準'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='qc_metrics',
            field=models.JSONField(blank=True, default=list, help_text='存放當次生產的各項檢測數值與結果', null=True, verbose_name='品管檢驗與批號紀錄'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='qc_passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='品管是否合格'),
        ),
    ]
