# Generated by Django 6.0.4 on 2026-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0066_remove_material_qc_brix_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='sequence_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='投入序號'),
        ),
    ]
