# Generated by Django 6.0.4 on 2026-10-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0067_bom_sequence_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True, verbose_name='製造日期'),
        ),
    ]
