# Generated by Django 6.0.4 on 2026-10-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0068_productionorder_manufacture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='source_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_ingredients', to='factory.material', verbose_name='來源物料'),
        ),
    ]
