# Generated by Django 6.0.4 on 2026-10-07 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0069_ingredient_source_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscTransactionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(verbose_name='交易日期')),
                ('transaction_type', models.CharField(choices=[('INCOME', '收入 (如: 提領零用金)'), ('EXPENSE', '支出 (如: 雜支、電話費)')], max_length=20, verbose_name='收支類型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金額')),
                ('category', models.CharField(help_text='如：電話費、維修費、提領零用金', max_length=100, verbose_name='類別')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '雜支與零用金紀錄',
                'db_table': 'misc_transaction_records',
            },
        ),
        migrations.CreateModel(
            name='MiscTransactionRecordLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.misctransactionrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'misc_transaction_record_logs',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(verbose_name='收付款日期')),
                ('partner_type', models.CharField(choices=[('CUSTOMER', '客戶 (收款)'), ('VENDOR', '廠商 (付款)')], max_length=20, verbose_name='對象類型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金額')),
                ('payment_method', models.CharField(choices=[('CASH', '現金'), ('TRANSFER', '匯款'), ('CHECK', '支票/票據')], max_length=20, verbose_name='付款方式')),
                ('check_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='支票與票據資訊')),
                ('reference_notes', models.TextField(blank=True, help_text='會計可輸入沖銷的銷貨單號或發票號碼', null=True, verbose_name='沖銷與備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='若為客戶收款請填此欄', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='factory.vendor', verbose_name='客戶')),
                ('provider', models.ForeignKey(blank=True, help_text='若為廠商付款請填此欄', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='factory.materialprovider', verbose_name='廠商')),
            ],
            options={
                'verbose_name': '金流收付款紀錄',
                'db_table': 'payment_records',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecordLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='factory.paymentrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_record_logs',
            },
        ),
    ]
